name: Build external wheels

on:
  release:
    types:
      - published
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Setup python build
        run: |
          python -m pip install build

      - name: Build scikit-bio
        working-directory: ext/scikit-bio
        run: |
          python -m build
          python -m build --wheel

      - name: Upload scikit-bio
        uses: actions/upload-artifact@v3
        with:
          name: scikit-bio.whl
          path: ext/scikit-bio/build/*.whl
